services:
  - type: web
    name: my-django-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chatbot_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chatbot_project.settings
      - key: SECRET_KEY
        generateValue: true
